import{a as p,i as n,S as y}from"./assets/vendor-DEenWwFD.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const f=r=>r.map(({largeImageURL:e,webformatURL:o,tags:l,likes:t,views:s,comments:c,downloads:v})=>`<li class="gallery-item">
      <a class="gallery-link" href="${e}">
          <img
            src="${o}"
            alt="${l}"
            class="gallery-img img-fluid" loading="lazy" 
          />
          <div class="text-list">
              <p class="text-likes">Likes: ${t}</p>
              <p class="text-views">Views: ${s}</p>
              <p class="text-comments">Comments: ${c}</p>
              <p class="text-downloads">Downloads: ${v}</p>
          </div>
        </a>
      </li>`).join(""),w="47936251-08966a92c9e59538871cb9ab8",L="https://pixabay.com/api/";p.defaults.baseURL=L;const h=15,b=(r,e=1)=>{const o=new URLSearchParams({q:r,key:w,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:h,page:e});return p(L,{params:o})},d=document.querySelector(".js-gallery"),P=document.querySelector(".js-search-form"),m=document.querySelector(".loader"),a=document.querySelector(".btn-more");let i=1,g=0,u;a.classList.add("d-none");async function S(r){r.preventDefault();const e=r.currentTarget;if(u=e.elements.searchKeyword.value,d.innerHTML="",a.classList.add("d-none"),u.trim()===""){n.error({message:"Input field can not be empty",color:"red",position:"topRight",timeout:2e3,close:!0}),e.reset();return}d.innerHTML="",m.classList.remove("is-hidden");try{const{data:o}=await b(u);if(o.total===0){n.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"red",timeout:2e3,close:!0});return}d.insertAdjacentHTML("beforeend",f(o.hits)),new y(".js-gallery a",{captionPosition:"bottom",captionDelay:250,captionsData:"alt"}).refresh(),h<o.total?(g=Math.ceil(o.total/h),console.log(i),g>1&&a.classList.remove("d-none")):n.show({message:"We're sorry, but you've reached the end of search results",position:"topRight",color:"red",timeout:2e3,close:!0})}catch(o){console.log(o)}e.reset(),m.classList.add("is-hidden"),i=1}const x=()=>{const o=d.querySelector(".gallery-item").getBoundingClientRect().height*2;window.scrollBy({top:o,left:0,behavior:"smooth"})},E=async r=>{try{i+=1,a.classList.remove("d-none"),m.classList.remove("is-hidden");const{data:e}=await b(u,i);e.total===0&&(a.classList.add("d-none"),m.classList.add("is-hidden"),n.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"red",timeout:2e3,close:!0})),d.insertAdjacentHTML("beforeend",f(e.hits)),m.classList.add("is-hidden"),new y(".js-gallery a",{captionPosition:"bottom",captionDelay:250,captionsData:"alt"}).refresh(),x(),0<e.total-h*i?g>1&&a.classList.remove("d-none"):a.classList.add("d-none"),i>=g&&n.show({message:"We're sorry, but you've reached the end of search results",position:"topRight",color:"red",timeout:2e3,close:!0})}catch{n.error({message:"Search params is not valid!",color:"red",position:"topRight",timeout:2e3,close:!0})}};P.addEventListener("submit",S);a.addEventListener("click",E);
//# sourceMappingURL=index.js.map
